
[package]
name = "solanasuper_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
prost = "0.12"
thiserror = "1.0"

[build-dependencies]
prost-build = "0.12"
