[package]
name = "solanasuper_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
prost = "0.9"
prost-types = "0.9"
getrandom = "=0.2.17"
log = "0.4"
android_logger = "0.13"


